// config.h - Generated by EX-Installer v0.0.16 for EX-CommandStation v5.0.9-Prod

#define IP_PORT 2560
#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD
#define LCD_DRIVER 0x27,20,4
#define SCROLLMODE 1
#define ENABLE_ETHERNET true
#define IP_ADDRESS { 192, 168, 0, 13 }
#define SERIAL3_COMMANDS
